apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sts
  labels:
    app: mongo-sts
spec:
  serviceName: mongo-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongo-sts
  template:
    metadata:
      labels:
        app: mongo-sts
        version: v1
    spec:
      containers:
      - name: mongo
        image: mongo:4.2
        command:
        - bash
        - /config/init.sh
        ports:
        - containerPort: 27017
          name: mongo
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: mongo-db
          mountPath: /data/db
        - name: mongo-config
          mountPath: /config
      volumes:
      - name: mongo-db
        persistentVolumeClaim:
          claimName: mongo-db-pvc
      - name: mongo-config
        configMap:
          name: mongo-config