apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spspnamespace
  namespace: default
spec:
  crd:
    spec:
      names:
        kind: K8sPSPNamespace
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8spspnamespace

        violation[{"msg": msg, "details": {}}] {
          input.review.object.metadata.namespace != "kube-system"
          input.review.object.metadata.namespace != "default"
          input.review.object.metadata.namespace != "production"
          input.review.object.metadata.namespace != "staging"
          msg = sprintf("Namespace '%v' is not allowed", [input.review.object.metadata.namespace])
        }