apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spsplimitcontainer
  namespace: default
spec:
  crd: #
    spec:
      names: 
        kind: K8sPSPLimitContainer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package limitsresources
        default limit = -1
        violation[{"msg": msg, "details": {}}] {
          container := input.review.object.spec.containers[_]
          container.resources.limits.memory <= limit
          msg = sprintf("Container '%v' has memory limit '%v' which is less than the allowed limit '%v'", [container.name, container.resources.limits.memory, limit])
        }